### PR TITLE
update for free account plus a couple of fixes

### PR DESCRIPTION
**Pull request by cookieisland**
1) Added automatic ability for streams to be refreshed prior to the Locast free user timeout.  This was inspired by the work @rocky4546 originally did back in December.  I took a different approach utilizing the background service to refresh the playing stream after a period of time specified in the configuration menu.

2) Fixed login error for free users.  Since a free user will have a donationExpire of "" it will cause the 'login' function to have an exception.  Also forced re-login for users who do not have User_Donate properly set.

3) inputstream.adaptive does not work on my Odroid N2 running CoreELEC v19.  Launching a channel from the addon's 'live' option hangs for about 5-10 seconds and then the video starts playing behind the menu.  Looking at the log it seem like adaptive is attempted, fails and reverts to ffmpeg. When launched from the IPTV Simple EPG it does not work at all.  inputstream.ffmpegdirect works fine so I made an option in the configuration menu to request ffmpegdirect.

### CODE REVIEW

**Comment by cookieisland** [comment]
900 seconds for refresh turns out to be too aggressive and can periodically cause a problem. Now I the default set to 824 which is what @rocky4546  originally used. If you are testing using the original commit you will likely need to change your refresh time in configuration settings manually.

Also adjusted refresh timing for updating playlist.

**Comment by Lunatixz** [comment]
Thanks for your PR! however, I can not accept it as is. There are a number of issues and changes I do not agree with and are not Kodi repository permitted code. Either unorthodox methods or shoehorned functions.

For example, pseudotv_recommened should have been left alone any "services" ought to be made in a standalone method. I'm also unsure of what you are trying to attempt by running this service. Why is it needed?

Second, you are incorrectly calling Player().play this call is limited to services, not plugins. Also, the while loop within the playback call is unusual and something I would not use.

Thanks for catching the exception that is raised for the donationexpired meta, I'll correct that.

BTW why are you attempting to bypass the 15min cache in getURL what is the reasoning?

If you explain to me the features you are looking to add, perhaps I can add them myself. Since it appears you are new to Kodi plugin development. 

THX

**Comment by cookieisland** [comment]
Thanks Lunatixz,  
Let me try to explain my logic...  

With a free Locast account after about 15 minutes the Locast stream is interrupted and switches to a video message that says something like  'thanks for using Locast... please donate $5/month'. The user then needs to use their remote to stop the playback returning to the Locast menu or IPTV EPG and then user then needs to restart the stream manually. With this enhancement the plugin will automatically restart the stream prior to the timeout thus avoiding the timeout altogether.

In the PR that @rocky4546 submitted he/she addressed this by creating a thread in the main plugin to wait for about 14 minutes and then restart the stream to avoid the timeout. The problem I saw with that was the plugin kept running continuously which I don't think it is supposed to do. Since the service is allowed to run continuously I thought that would be the better place to monitor the playback and take actions.

I would much rather not have modified pseudotv_recommended. Originally I tried to make a second standalone service in addition to pseudotv_recommended. However I could not seem to define two extensions of type xbmc.service in addon.xml. When I did, only the first service was used.  Is there a way that you know of to have a 2nd service for the plugin? 

I wondered if using Play().play may be questionable but was not sure. The goal was to wait the appropriate amount of time after a Locast playback stream was started and then trigger the main plugin to start a new stream URL. I was able to do this with Player().play with something similar to 'plugin://plugin.video.locast/play/live/1234'   Is there another way to trigger the main plugin from a background service? Maybe I should create a standalone script or service addon?  If I did that, free Locast users that want this enhancement would need to install a 2nd addon called something like "Locast Free Assistant".

The code I added after the setResolvedUrl in the main plugin was due to the playlist being lost when the currently running stream stopped and new stream started. Even though the playlist was properly set prior to calling setResolvedUrl it ended up getting cleared anyway.  I was able to fix this by resetting the playlist after calling setResolvedUrl (but I had to wait 1 second after setResolvedUrl to set the playlist).  The while loop in the playback was an attempt to be more precise.  Instead of waiting a fixed amount of time (1 sec) it waits for the playback to start and then recreates the cleared playlist.  

I bypassed the 15 min cache because for a free account the stream URL returned by Locast will only be valid for 15 minutes after it was created by the Locast api call. Here is an example: Thus if a person started playback on channel#1 and watched it for 6 minutes, then looked at channel#2 for 6 minutes, and then finally deciding to go back to channel#1 again it (channel#1) would timeout after about 3 minutes and you would get the 'thanks for using Locast' message and the user would have to stop and start the playback manually.

Hope this makes sense.... Sorry for being longwinded....

**Comment by Lunatixz** [comment]
Starters... I'm not for bypassing or circumventing any trial periods / region locks in locast...

The idea of a companion script to do anything remotely like it would end up banned from the Kodi forums and labeled piracy.

I believe you might be mistaken in assuming the feed cuts out, rather I believe the donation ad is rolled into the stream; a bug within inputstream is not catching the stream redirect after the "ad". Which appears to freeze?

If this is the case it's an easy fix to reconnect inputstream and does not require services to reengage.

However, if this is by design and locast does not offer extended trials beyond a given play through. My code will remain as is.

Hope you understand,

Thx

**Comment by cookieisland** [comment]
I totally understand and appreciate the info. I don't want to be part of piracy either.

**Comment by Lunatixz** [comment]
Great, I'll work on figuring out the issues with free accounts to assure I'm providing a good mix of usability while respecting the rules of the service.

**Comment by cookieisland** [comment]
I will test  your update when I see it. Meantime I will close this PR.

**Comment by rocky4546** [comment]
Sorry, I have been on rolling blackouts with temperatures below zero.  Electricity just came back on.  For the free account design, here is how it is suppose to work.  Locast sends a m3u file that contains a 6 second ad at the start.  Then, it will replenish the M3U until 900 seconds has expired.  It finally sends a second 6 second ad before it terminates that stream.  When you restart the stream, Locast will again send a 6 second ad before playing the normal video for about 900 seconds.

The design is to refresh the stream BEFORE the 900 seconds is up.  This is critical since the plugin has no idea if and when locast terminates the stream.  Once refreshed, Locast will again send the 6 second starting ad followed by an additional 900 seconds of video.  So, the implementation is simple.  Refresh the stream at an interval that is less than the timeout/ad time of 900 seconds to keep the stream flowing.

**Comment by Lunatixz** [comment]
Sorry to hear... Texas?

Thanks for the info; However, this PR's implementation of this "refresh" concept is anything but simple... it's brute and overkill to achieve its goal. Inputstream was designed for this exact use-case....  and will only require a single line of code... I will push the fix shortly.

**Comment by rocky4546** [comment]
Yes, Texas.  On top of the rolling blackout, the natural gas pumps froze, so the pressure to light the furnace was also an issue.  So when you are down 10-18 hours and things come back online, all the heaters in the area turned on at once making the gas pressure non-existent. It was insane for a while there.

I understand what you are saying on the PR.  And, BTW, I am absolutely for compliance with licenses.  I have been a security engineer for decades and understand compliance. Since you know a ton more than me on Kodi, you may be able to come up with a better solution.  The hard part was when the user changed channels.  Each channel is a separate thread with separate refreshes, so you do not want to be refreshing an old stream that the user has dropped.  If the Kodi video window is still running on a different channel, Kodi will switch to broadcast that old channel on refresh, lol.  So things get very confused real fast if the user is changing channels a ton.  Knowing when to drop a channel refresh was the reason for most of the code.

**Comment by cookieisland** [comment]
Thanks Lunatixz!
I have tested tested with 1.1.3a
1) I can login with a free Locast account. However the 'last login' field on the configuration screen does not get updated. With the change I made in the PR that field was updated.
2) When playing from the iptv EPG the channels now play ok again.
3) When playing directly from the addon (eg when I select a channel from the addon's "Live" menu) I get viewing problems. What happens when you select a channel from the menu is the channel the channel selection menu does not go away. It stays in the foreground and the video starts playing behind the menu.  Prior to the 1.1.3 update (where inputstreamaddon was changed to inputstream) selecting a channel would play the channel properly (the video would go full screen and no menu would be visible - unless you hit ESC of course)


I will watch for your next update with inputstream reconnect code and will test that. One line of code to handle the refresh would be amazing! I will be even more embarrassed with my attempt - but I had time and I learned a lot so that is good.

**Comment by Lunatixz** [comment]
@cookieisland no need to be embarrassed... I appreciate your help and it was not a slight on your PR. I've been doing this for a long time...

**Comment by cookieisland** [comment]
@rocky4546  stay warm. Well, as warm as you can.  I hope your gas supply gets back to normal quickly.

**Pull request closed without merging**
