### PR TITLE
Revert "Translations update from Kodi Weblate"

### PR DESCRIPTION
**Pull request by gspot31**
Reverts Lunatixz/KODI_Addons#189

### CODE REVIEW

**Comment by gade01** [comment]
@Lunatixz @gspot31 
Why was this reverted?
All translations at Weblate were removed with this PR.
Now we have merge conflicts.

Translations should never be touched directly at Github, but at Weblate instead.
Only en_gb file should be handled at Github.

**Comment by Lunatixz** [comment]
I'm not sure what you mean. I only merge Translation PR requests; if a revert PR is created; I assume it is to correct an error.
What PR would you like me to change?

**Comment by gade01** [comment]
Ah, I see.
No worries, I'll explain. 

This PR https://github.com/Lunatixz/KODI_Addons/pull/190 is not from me or Weblate. 
Language PR's should mostly come from me or Weblate directly. 

@gspot31 is not a user at Weblate or part of Team Kodi.
So I'm not why this PR was created.

We have had spam PR's similar to this created for other XBMC org repos.

Another time, don't hesitate to contact me :)

**Comment by Lunatixz** [comment]
Sorry about that, since the PR was not code-related I failed to do my due diligence to verify its origins.
I created a PR and will make sure only to accept PR's from you or weblate, thx

**Comment by gade01** [comment]
@Lunatixz 
No worries at all and no harm done.
Thanks so much for looking into this and fixing it so fast. :)

**Pull request merged**
