### PR TITLE
Improved: getChanneldata

### PR DESCRIPTION
**Pull request by michlinux**
Improved getChanneldata to get all epg data from site api.

### CODE REVIEW

**Comment by Lunatixz** [comment]
Thanks

**Comment by Lunatixz** [comment]
Few issues, but thanks for the help; missing function/variable; not the methods of the class. getURL/headers. Also, there are duplicate channel entries we'll need to 'filter' out, also the returns have way too many entries maybe duplicates? seeing 400+ items. I'll revert for now, but thank you feel free to contribute when you can :)

**Comment by michlinux** [comment]
awe, sorry... need self. ive been rewriting my script since ustvnow "broke" everything more that parses live urls and epg to xmltv. I didn't notice the epg duplicates because my xmltv building function filters them. I thought I tested it before before a sent the request, but I used the wrong kodi which had the current. sorry half awake- will look at more later. cheers

**Comment by michlinux** [comment]
also in my script that same basic code returns 10 days worth of epg data(This seams to be the max), so there is a lot... which is what i want for xmltv.... maybe be a bit to much for kodi?

**Comment by Lunatixz** [comment]
10 days is way too much, even for an xmltv file... its good practice to use 3 days. You want to limit parsing while keeping data fresh.

**Comment by Lunatixz** [comment]
Are you using the XMLTV for Kodi, IPTV simple setup? Back in the day, I had a xmltv and m3u generator built into the plugin. If the need is there I can add it back...

**Pull request merged**
